name: Docs v1
on: 
  push:
    branches:
      - main

permissions:
  contents: write

env:
  NODE_VERSION: 22.14.x
  DOCS_PATH: docs/v1

  SWA_NAME: "thaitype-kubricate"

  # Retry Config
  RETRY_TIMEOUT_MINUTES: 2
  RETRY_MAX_ATTEMPTS: 3
  RETRY_DELAY_SECONDS: 5

jobs:
  build-deploy:
    name: Build and Deploy
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: pnpm i

      - name: Generate API Docs
        run: pnpm typedoc
        working-directory: ${{ env.DOCS_PATH }}

      - name: Doc Build
        run: pnpm build
        working-directory: ${{ env.DOCS_PATH }}

      - name: Deploy to Azure Static Web Apps
        uses: nick-fields/retry@v2.8.3
        with:
          timeout_minutes: ${{ env.RETRY_TIMEOUT_MINUTES }}
          max_attempts: ${{ env.RETRY_MAX_ATTEMPTS }}
          polling_interval_seconds: ${{ env.RETRY_DELAY_SECONDS }}
          command: npx @azure/static-web-apps-cli deploy ${{ env.DOCS_PATH }}/.vitepress/dist --env production -n  ${{ env.SWA_NAME }}
        env:
          SWA_CLI_DEPLOYMENT_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_WATER_084BCB900 }}